<a href="https://colab.research.google.com/github/hyunmingit/Colab/blob/master/Ch01/2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
Numpy 라이브러리
 - 고성능 수치계산을 위한 파이썬 라이브러리
 - 파이썬 기본 리스트 보다 더 크고 빠른 연산을 위한 리스트를 제공
 - 행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np

In [3]:
v1 = np.array([1, 2, 3, 4, 5])
print(v1)

v2 = np.arange(10)
print(v2)

v3 = np.arange(100)
print(v3)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [4]:
rand1 = np.random.rand(100)
rand1

array([0.03617793, 0.52292819, 0.93853841, 0.74934999, 0.18846162,
       0.47604842, 0.73570141, 0.20368557, 0.11981932, 0.27381801,
       0.51307743, 0.72260736, 0.9576865 , 0.92447278, 0.87477976,
       0.05467036, 0.70143586, 0.83029639, 0.50444786, 0.0225887 ,
       0.00676651, 0.80311968, 0.11423028, 0.69726365, 0.93577543,
       0.54744307, 0.20851092, 0.9542776 , 0.61266712, 0.35365396,
       0.64424525, 0.98399861, 0.66316115, 0.24710304, 0.27115634,
       0.53566349, 0.63852999, 0.91229321, 0.54278959, 0.42140788,
       0.85010178, 0.28018239, 0.48470329, 0.9761342 , 0.46260862,
       0.85833862, 0.14245206, 0.22469828, 0.04956122, 0.81251549,
       0.42775081, 0.10064936, 0.04494468, 0.40307698, 0.24966856,
       0.05341158, 0.20547473, 0.01888103, 0.24157071, 0.0113285 ,
       0.18145363, 0.03898109, 0.04723343, 0.91002333, 0.62858749,
       0.81998036, 0.88115284, 0.33982767, 0.56083882, 0.75553168,
       0.74467666, 0.81939893, 0.25521678, 0.53384501, 0.38306

In [5]:
#표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-4.51831951e-01, -8.75036368e-01,  7.74372868e-01, -5.06168908e-01,
        7.60484161e-01,  3.21707077e-01, -2.16128827e+00, -1.28671074e+00,
       -4.32544337e-01, -9.54150593e-01, -3.30249700e-01,  2.37633272e-02,
       -7.28394804e-01, -1.26202303e+00, -1.91774176e+00,  4.36851831e-01,
       -2.74491805e+00, -5.17269597e-01, -2.49489637e-01, -2.66919450e-01,
       -5.23179896e-01,  1.84123849e+00, -9.83017212e-01, -2.95182248e-01,
        6.93591529e-01, -5.95290872e-01,  3.87338697e-01,  9.07205602e-01,
       -5.09100040e-01,  8.15502740e-01, -7.16302149e-01, -1.87451659e+00,
       -2.92008213e-01, -9.94639978e-01,  7.90931128e-01, -1.22078814e-02,
        4.98846085e-01,  6.13432736e-02,  3.50869700e-01, -5.10829607e-01,
        7.25136577e-01,  1.21331566e+00,  1.47822422e+00,  2.73177007e-01,
       -1.47668346e+00, -5.29752415e-01, -4.65974172e-01, -9.24264320e-01,
        1.69794492e-01,  1.25965939e+00, -6.03659658e-01, -8.19593870e-01,
        2.97104621e-01, -

In [8]:
m1 = np.array([[1, 2],[3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.zeros([2, 3])
print(m3)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
im1 = np.linalg.inv(m1)
print(im1)

result = m1.dot(im1)
print(result.round())

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [20]:
mat = np.array([[1,2,3,4], [5,6,7,8,], [9,10,11,12]])
print(mat)

print(mat[0, 0])
print(mat[0, :])
print(mat[:, 0])
print('================')
print(mat[0:2, 0:2])
print('================')
print(mat[:, 0:2])
print('================')
print(mat[:, 2:4])
print('================')
print(mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
